// Mock data source. Swap to SQLite + Node server functions later —
// each export is the shape the future backend should return.

export type Drive = {
  id: string;
  label: string;
  mount: string;
  fs: string;
  totalGB: number;
  usedGB: number;
};

export const drives: Drive[] = [
  { id: "c", label: "System", mount: "C:\\", fs: "NTFS", totalGB: 476, usedGB: 312 },
  { id: "d", label: "Data", mount: "D:\\", fs: "NTFS", totalGB: 931, usedGB: 604 },
  { id: "e", label: "Backup", mount: "E:\\", fs: "exFAT", totalGB: 1863, usedGB: 421 },
];

export type CleanupCategory = {
  id: string;
  name: string;
  sizeMB: number;
  files: number;
  risk: "safe" | "review" | "caution";
  description: string;
  requiresAdmin?: boolean;
  requiresRestart?: boolean;
};

export const cleanupCategories: CleanupCategory[] = [
  { id: "win-temp", name: "Windows temporary files", sizeMB: 2841, files: 12043, risk: "safe", description: "Cache from Windows and installers. Windows will recreate as needed." },
  { id: "user-temp", name: "User temporary files", sizeMB: 1204, files: 8321, risk: "safe", description: "%TEMP% for the current user." },
  { id: "win-update", name: "Windows Update cache", sizeMB: 6532, files: 214, risk: "review", description: "Downloaded update payloads. Removing may re-download on next update.", requiresAdmin: true },
  { id: "delivery-opt", name: "Delivery Optimization files", sizeMB: 3120, files: 89, risk: "review", description: "Peer-to-peer update cache." },
  { id: "thumbnails", name: "Thumbnail cache", sizeMB: 342, files: 1, risk: "safe", description: "Explorer thumbnails, regenerated on demand." },
  { id: "dx-shader", name: "DirectX shader cache", sizeMB: 812, files: 47, risk: "safe", description: "GPU shader cache; regenerated by games." },
  { id: "crash-dumps", name: "Crash dumps", sizeMB: 1902, files: 23, risk: "review", description: "Kernel/user minidumps. Useful for diagnostics." },
  { id: "error-reports", name: "Windows error reports", sizeMB: 218, files: 412, risk: "safe", description: "Queued and archived WER reports." },
  { id: "installer-left", name: "Installer leftovers", sizeMB: 972, files: 58, risk: "review", description: "MSI/EXE payloads left in %ProgramData%." },
  { id: "browser-cache", name: "Browser cache", sizeMB: 1487, files: 22103, risk: "safe", description: "Chromium/Edge/Firefox cached assets." },
  { id: "recycle-bin", name: "Recycle Bin", sizeMB: 4210, files: 342, risk: "review", description: "Restorable until emptied." },
  { id: "old-logs", name: "Old log files (>30d)", sizeMB: 512, files: 803, risk: "safe", description: "Application and system log rotation." },
  { id: "broken-shortcuts", name: "Broken shortcuts", sizeMB: 1, files: 27, risk: "safe", description: "Start Menu and Desktop shortcuts with missing targets." },
  { id: "prev-windows", name: "Previous Windows installation", sizeMB: 24380, files: 1, risk: "caution", description: "C:\\Windows.old — required to roll back a feature update.", requiresAdmin: true, requiresRestart: true },
];

export const usageByType = [
  { type: "Video", gb: 148 },
  { type: "Games", gb: 96 },
  { type: "Apps", gb: 54 },
  { type: "Documents", gb: 32 },
  { type: "Images", gb: 28 },
  { type: "System", gb: 41 },
  { type: "Other", gb: 19 },
];

export const largestFolders = [
  { path: "C:\\Users\\alex\\Videos\\Recordings", sizeGB: 84.2, items: 214 },
  { path: "C:\\Program Files\\Epic Games", sizeGB: 61.7, items: 4802 },
  { path: "C:\\Users\\alex\\AppData\\Local\\Docker", sizeGB: 38.4, items: 1204 },
  { path: "D:\\Projects\\node_modules-graveyard", sizeGB: 22.1, items: 84302 },
  { path: "C:\\Users\\alex\\Downloads", sizeGB: 17.9, items: 612 },
  { path: "C:\\Windows\\Installer", sizeGB: 14.2, items: 342 },
];

export type LargeFile = {
  name: string;
  path: string;
  sizeMB: number;
  modified: string;
  kind: string;
};

export const largeFiles: LargeFile[] = [
  { name: "windows11.iso", path: "C:\\Users\\alex\\Downloads", sizeMB: 5842, modified: "2026-02-11", kind: "ISO" },
  { name: "backup-2025-12.vhdx", path: "E:\\Backups", sizeMB: 42180, modified: "2025-12-31", kind: "VM Disk" },
  { name: "screen-recording.mkv", path: "C:\\Users\\alex\\Videos", sizeMB: 8412, modified: "2026-05-04", kind: "Video" },
  { name: "dataset.parquet", path: "D:\\Datasets", sizeMB: 3204, modified: "2026-06-18", kind: "Data" },
  { name: "project-archive.7z", path: "D:\\Archives", sizeMB: 2984, modified: "2025-09-02", kind: "Archive" },
];

export type DuplicateGroup = {
  hash: string;
  sizeMB: number;
  copies: { path: string; modified: string }[];
};

export const duplicateGroups: DuplicateGroup[] = [
  {
    hash: "a1b2c3d4",
    sizeMB: 412,
    copies: [
      { path: "C:\\Users\\alex\\Pictures\\trip.mp4", modified: "2025-08-11" },
      { path: "D:\\Backup\\phone\\trip.mp4", modified: "2025-08-12" },
      { path: "E:\\Archive\\2025\\trip.mp4", modified: "2025-09-01" },
    ],
  },
  {
    hash: "e5f6a7b8",
    sizeMB: 128,
    copies: [
      { path: "C:\\Users\\alex\\Downloads\\installer.exe", modified: "2025-11-04" },
      { path: "C:\\Users\\alex\\Desktop\\installer.exe", modified: "2025-11-04" },
    ],
  },
  {
    hash: "c9d0e1f2",
    sizeMB: 86,
    copies: [
      { path: "D:\\Music\\album\\01.flac", modified: "2024-03-19" },
      { path: "D:\\Music\\album (1)\\01.flac", modified: "2024-03-19" },
      { path: "E:\\Backup\\Music\\01.flac", modified: "2024-04-02" },
    ],
  },
];

export type InstalledApp = {
  id: string;
  name: string;
  publisher: string;
  version: string;
  sizeMB: number;
  installed: string;
  source: "desktop" | "store";
  lastUsed?: string;
};

export const installedApps: InstalledApp[] = [
  { id: "vscode", name: "Visual Studio Code", publisher: "Microsoft", version: "1.98.2", sizeMB: 412, installed: "2024-11-02", source: "desktop", lastUsed: "2026-07-23" },
  { id: "chrome", name: "Google Chrome", publisher: "Google LLC", version: "142.0.7204", sizeMB: 684, installed: "2024-08-14", source: "desktop", lastUsed: "2026-07-24" },
  { id: "steam", name: "Steam", publisher: "Valve", version: "3.8.4", sizeMB: 892, installed: "2023-06-01", source: "desktop", lastUsed: "2026-07-22" },
  { id: "office", name: "Microsoft 365", publisher: "Microsoft", version: "2405", sizeMB: 3204, installed: "2024-01-10", source: "desktop", lastUsed: "2026-07-20" },
  { id: "photoshop", name: "Adobe Photoshop", publisher: "Adobe", version: "25.9", sizeMB: 4820, installed: "2024-10-18", source: "desktop", lastUsed: "2026-01-04" },
  { id: "spotify", name: "Spotify", publisher: "Spotify AB", version: "1.2.42", sizeMB: 214, installed: "2024-05-30", source: "store", lastUsed: "2026-07-24" },
  { id: "obs", name: "OBS Studio", publisher: "OBS Project", version: "30.2.3", sizeMB: 342, installed: "2025-02-11", source: "desktop", lastUsed: "2026-05-14" },
  { id: "docker", name: "Docker Desktop", publisher: "Docker Inc.", version: "4.34.0", sizeMB: 1820, installed: "2024-09-12", source: "desktop", lastUsed: "2026-07-18" },
];

export type StartupEntry = {
  id: string;
  name: string;
  publisher: string;
  path: string;
  enabled: boolean;
  impact: "low" | "medium" | "high";
  source: "registry" | "folder" | "task";
};

export const startupEntries: StartupEntry[] = [
  { id: "onedrive", name: "OneDrive", publisher: "Microsoft", path: "C:\\Users\\alex\\AppData\\Local\\Microsoft\\OneDrive\\OneDrive.exe", enabled: true, impact: "medium", source: "registry" },
  { id: "spotify", name: "Spotify", publisher: "Spotify AB", path: "%APPDATA%\\Spotify\\Spotify.exe", enabled: true, impact: "high", source: "registry" },
  { id: "steam", name: "Steam", publisher: "Valve", path: "C:\\Program Files (x86)\\Steam\\steam.exe -silent", enabled: false, impact: "high", source: "registry" },
  { id: "discord", name: "Discord", publisher: "Discord Inc.", path: "%LOCALAPPDATA%\\Discord\\Update.exe", enabled: true, impact: "medium", source: "folder" },
  { id: "docker", name: "Docker Desktop", publisher: "Docker Inc.", path: "C:\\Program Files\\Docker\\Docker\\Docker Desktop.exe", enabled: true, impact: "high", source: "task" },
  { id: "teams", name: "Microsoft Teams", publisher: "Microsoft", path: "%LOCALAPPDATA%\\Microsoft\\Teams\\Update.exe", enabled: false, impact: "medium", source: "registry" },
];

export type QuarantineItem = {
  id: string;
  originalPath: string;
  sizeMB: number;
  deletedAt: string;
  category: string;
  expiresAt: string;
};

export const quarantine: QuarantineItem[] = [
  { id: "q1", originalPath: "C:\\Users\\alex\\AppData\\Local\\Temp\\setup_9182.tmp", sizeMB: 128, deletedAt: "2026-07-22 14:02", category: "User temp", expiresAt: "2026-08-21" },
  { id: "q2", originalPath: "C:\\Windows\\SoftwareDistribution\\Download\\3a8...", sizeMB: 2410, deletedAt: "2026-07-20 09:41", category: "Windows Update cache", expiresAt: "2026-08-19" },
  { id: "q3", originalPath: "C:\\Users\\alex\\Downloads\\old-installer.exe", sizeMB: 84, deletedAt: "2026-07-18 22:15", category: "Installer leftovers", expiresAt: "2026-08-17" },
];

export type Activity = {
  when: string;
  action: string;
  detail: string;
  freedMB?: number;
};

export const activity: Activity[] = [
  { when: "2026-07-24 08:12", action: "Scan", detail: "Full storage analysis on C:\\, D:\\" },
  { when: "2026-07-22 14:02", action: "Clean", detail: "User temp + browser cache", freedMB: 3820 },
  { when: "2026-07-20 09:41", action: "Clean", detail: "Windows Update cache", freedMB: 6410 },
  { when: "2026-07-18 22:15", action: "Duplicates", detail: "Moved 12 duplicates to quarantine", freedMB: 942 },
  { when: "2026-07-15 10:03", action: "Startup", detail: "Disabled Steam auto-launch" },
];

export function formatSize(mb: number): string {
  if (mb >= 1024) return `${(mb / 1024).toFixed(1)} GB`;
  return `${mb.toFixed(0)} MB`;
}

export function formatGB(gb: number): string {
  if (gb >= 1024) return `${(gb / 1024).toFixed(2)} TB`;
  return `${gb.toFixed(1)} GB`;
}
