/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StorageRouteImport } from './routes/storage'
import { Route as StartupRouteImport } from './routes/startup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TrashRouteImport } from './routes/trash'
import { Route as LargeFilesRouteImport } from './routes/large-files'
import { Route as FilesRouteImport } from './routes/files'
import { Route as DuplicatesRouteImport } from './routes/duplicates'
import { Route as CleanerRouteImport } from './routes/cleaner'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as IndexRouteImport } from './routes/index'

const StorageRoute = StorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => rootRouteImport,
} as any)
const StartupRoute = StartupRouteImport.update({
  id: '/startup',
  path: '/startup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TrashRoute = TrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => rootRouteImport,
} as any)
const LargeFilesRoute = LargeFilesRouteImport.update({
  id: '/large-files',
  path: '/large-files',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const DuplicatesRoute = DuplicatesRouteImport.update({
  id: '/duplicates',
  path: '/duplicates',
  getParentRoute: () => rootRouteImport,
} as any)
const CleanerRoute = CleanerRouteImport.update({
  id: '/cleaner',
  path: '/cleaner',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/cleaner': typeof CleanerRoute
  '/duplicates': typeof DuplicatesRoute
  '/files': typeof FilesRoute
  '/large-files': typeof LargeFilesRoute
  '/trash': typeof TrashRoute
  '/settings': typeof SettingsRoute
  '/startup': typeof StartupRoute
  '/storage': typeof StorageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/cleaner': typeof CleanerRoute
  '/duplicates': typeof DuplicatesRoute
  '/files': typeof FilesRoute
  '/large-files': typeof LargeFilesRoute
  '/trash': typeof TrashRoute
  '/settings': typeof SettingsRoute
  '/startup': typeof StartupRoute
  '/storage': typeof StorageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/applications': typeof ApplicationsRoute
  '/cleaner': typeof CleanerRoute
  '/duplicates': typeof DuplicatesRoute
  '/files': typeof FilesRoute
  '/large-files': typeof LargeFilesRoute
  '/trash': typeof TrashRoute
  '/settings': typeof SettingsRoute
  '/startup': typeof StartupRoute
  '/storage': typeof StorageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/applications'
    | '/cleaner'
    | '/duplicates'
    | '/files'
    | '/large-files'
    | '/trash'
    | '/settings'
    | '/startup'
    | '/storage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/applications'
    | '/cleaner'
    | '/duplicates'
    | '/files'
    | '/large-files'
    | '/trash'
    | '/settings'
    | '/startup'
    | '/storage'
  id:
    | '__root__'
    | '/'
    | '/applications'
    | '/cleaner'
    | '/duplicates'
    | '/files'
    | '/large-files'
    | '/trash'
    | '/settings'
    | '/startup'
    | '/storage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicationsRoute: typeof ApplicationsRoute
  CleanerRoute: typeof CleanerRoute
  DuplicatesRoute: typeof DuplicatesRoute
  FilesRoute: typeof FilesRoute
  LargeFilesRoute: typeof LargeFilesRoute
  TrashRoute: typeof TrashRoute
  SettingsRoute: typeof SettingsRoute
  StartupRoute: typeof StartupRoute
  StorageRoute: typeof StorageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/storage': {
      id: '/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof StorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/startup': {
      id: '/startup'
      path: '/startup'
      fullPath: '/startup'
      preLoaderRoute: typeof StartupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trash': {
      id: '/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof TrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/large-files': {
      id: '/large-files'
      path: '/large-files'
      fullPath: '/large-files'
      preLoaderRoute: typeof LargeFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duplicates': {
      id: '/duplicates'
      path: '/duplicates'
      fullPath: '/duplicates'
      preLoaderRoute: typeof DuplicatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cleaner': {
      id: '/cleaner'
      path: '/cleaner'
      fullPath: '/cleaner'
      preLoaderRoute: typeof CleanerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicationsRoute: ApplicationsRoute,
  CleanerRoute: CleanerRoute,
  DuplicatesRoute: DuplicatesRoute,
  FilesRoute: FilesRoute,
  LargeFilesRoute: LargeFilesRoute,
  TrashRoute: TrashRoute,
  SettingsRoute: SettingsRoute,
  StartupRoute: StartupRoute,
  StorageRoute: StorageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}

